# Generated by Django 5.1.6 on 2025-02-26 15:28

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_create_homepage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='homepage',
            old_name='featured_section_title',
            new_name='featured_pages_title',
        ),
        migrations.RenameField(
            model_name='homepage',
            old_name='introduction',
            new_name='hero_title',
        ),
        migrations.RemoveField(
            model_name='homepage',
            name='body',
        ),
        migrations.AddField(
            model_name='homepage',
            name='events_subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='events_title',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='guides_subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='guides_title',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='hero_subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='news_subtitle',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='homepage',
            name='news_title',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='homepage',
            name='hero_cta',
            field=wagtail.fields.StreamField([('link', 9)], blank=True, block_lookup={0: ('wagtail.blocks.CharBlock', (), {'form_classname': 'title', 'icon': 'title', 'required': True}), 1: ('wagtail.blocks.PageChooserBlock', (), {}), 2: ('wagtail.blocks.CharBlock', (), {'help_text': "Leave blank to use page's listing title.", 'required': False}), 3: ('wagtail.blocks.StructBlock', [[('page', 1), ('title', 2)]], {}), 4: ('wagtail.blocks.URLBlock', (), {}), 5: ('wagtail.blocks.CharBlock', (), {}), 6: ('wagtail.blocks.StructBlock', [[('link', 4), ('title', 5)]], {}), 7: ('wagtail.blocks.StreamBlock', [[('internal', 3), ('external', 6)]], {}), 8: ('wagtail.blocks.TextBlock', (), {'required': False}), 9: ('wagtail.blocks.StructBlock', [[('heading', 0), ('link', 7), ('description', 8)]], {})}),
        ),
    ]
