# Generated by Django 5.1.6 on 2025-02-26 15:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_rename_featured_section_title_homepage_featured_pages_title_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='homepage',
            name='featured_pages_title',
        ),
    ]
