version: 0.2

phases:

  pre_build:
    commands:
      - # Wait for docker
      - nohup /usr/local/bin/dockerd --host=unix:///var/run/docker.sock --host=tcp://127.0.0.1:2375 --storage-driver=overlay2 &
      - timeout 15 sh -c "until docker info; do echo .; sleep 1; done"
      - docker --version

  build:
    commands:
      # Build
      - make build
      - docker tag cplt-app $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/${TG_SUB_ENVIRONMENT}-ccs-intranet:latest

      # publish
      - aws ecr get-login-password --region $AWS_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com
      - docker push $AWS_ACCOUNT_ID.dkr.ecr.$AWS_REGION.amazonaws.com/${TG_SUB_ENVIRONMENT}-ccs-intranet:latest
