# Generated by Django 5.1.6 on 2025-02-26 15:34

import wagtail.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guides', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='guidepage',
            name='navigation',
            field=wagtail.fields.StreamField([('internal', 2), ('external', 5)], blank=True, block_lookup={0: ('wagtail.blocks.PageChooserBlock', (), {}), 1: ('wagtail.blocks.CharBlock', (), {'help_text': "Leave blank to use page's listing title.", 'required': False}), 2: ('wagtail.blocks.StructBlock', [[('page', 0), ('title', 1)]], {}), 3: ('wagtail.blocks.URLBlock', (), {}), 4: ('wagtail.blocks.CharBlock', (), {}), 5: ('wagtail.blocks.StructBlock', [[('link', 3), ('title', 4)]], {})}),
        ),
        migrations.AddField(
            model_name='guidepage',
            name='subtitle',
            field=models.TextField(blank=True),
        ),
    ]
